name: Deploy - Bicep
on:
  push:
    # branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v2.0.0
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./src/Infrastructure/bicep/main.bicep
          parameters: "sqlDatabasePassword=${{ secrets.SQL_DATABASE_PASSWORD }}"
          failOnStdErr: false
