name: Build & Test .NET Project

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version: '22.x'

    - name: Build Frontend
      run: |
        cd src/Clients/livepager.frontend
        npm run install
        npm run build

    - name: Restore workloads
      run: |
       dotnet workload install aspire
        
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
